export const HOUSES_LOADING = 'HOUSES_LOADING';
export const ADD_HOUSES = 'ADD_HOUSES';
export const HOUSES_FAILED = 'HOUSES_FAILED';

export const WORKORDERS_LOADING = 'WORKORDERS_LOADING';
export const ADD_WORKORDERS = 'ADD_WORKORDERS';
export const WORKORDERS_FAILED = 'WORKORDERS_FAILED';