export const WORK_ORDERS =
[
    {
        orderId: 0,
        orderType: 'Maintenance Order',
        houseId: 0,
        address: "1000 Golden Girl Lane",
        dateReported: "2018-10-25T16:30Z",
        dateAssigned: "",
        dateCompleted: "",
        completed: false,
        room: "Master Bathroom",
        description: "faucet leaking",
        Provider: "USA Ceiling Fans",
    },
    {
        orderId: 1,
        orderType: 'Maintenance Order',
        houseId: 0,
        address: "1000 Golden Girl Lane",
        dateReported: "2018-10-25T16:30Z",
        dateAssigned: "2018-10-25T16:30Z",
        dateCompleted: "2018-10-25T16:30Z",
        completed: true,
        room: "Master Bedroom",
        description: "Ceiling fan not working",
        Provider: "USA Ceiling Fans",
    },
    {
        orderId: 2,
        orderType: 'Maintenance Order',
        houseId: 0,
        address: "1000 Golden Girl Lane",
        dateReported: "2018-10-25T16:30Z",
        dateAssigned: "2018-10-25T16:30Z",
        dateCompleted: "2018-10-25T16:30Z",
        completed: true,
        room: "Kitchen",
        description: "Stove plug does not work",
        Provider: "USA Ceiling Fans",
    },
    {
        orderId: 3,
        orderType: 'Maintenance Order',
        houseId: 0,
        address: "1000 Golden Girl Lane",
        dateReported: "2018-10-25T16:30Z",
        dateAssigned: "2018-10-25T16:30Z",
        dateCompleted: "",
        completed: false,
        room: "Master Bedroom",
        description: "Ceiling fan not working",
        Provider: "USA Ceiling Fans",
    }
]
